baseURL = "https://yoursite.example.com/"
title = "Ensign blog"
# footnoteReturnLinkContents = "â†©"

# [permalinks]
# note = "/note/:year/:month/:day/:slug/"
# post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name =  "Home"
url =  ""
weight =  1
[[menu.main]]
name =  "About"
url =  "about/"
weight =  2
[[menu.main]]
name =  "Categories"
url =  "categories/"
weight =  3
[[menu.main]]
name =  "Tags"
url =  "tags/"
weight =  4
[[menu.main]]
name =  "Subscribe"
url =  "index.xml"