baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Ensign's blog"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true
