name = 'LCARS theme'
license = 'Custom'
licenselink = 'https://www.thelcars.com/license/'
description = 'A theme inspired by Star Trek LCARS system'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'scifi']
# features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  # {name = 'Name of author', homepage = 'Website of author'},
  # {name = 'Name of author', homepage = 'Website of author'}
  {name = 'Alessandro Bertulli', homepage = 'https://bertulli.github.io/ensign-blog'},
  {name = 'Jim Robertus', homepage = 'https://www.thelcars.com/'}
]

# If the theme has a single author
# [author]
#   name = ''
  

# If porting an existing theme
[original]
  author = 'Jim Robertus'
  homepage = 'https://www.thelcars.com/'
  repo = 'https://www.thelcars.com/download.php'
